const categories=['痛点问题类','情绪共鸣类','认知反差类','实用方法类','家庭关系类','自我成长类','金钱与变现类','故事案例类','争议讨论类','产品承接类'];
const titles=['为什么{人群}明明很努力，却总觉得没有进展？','你有没有发现，越想放松，内心反而越焦虑？','很多人误解了自律：真正有效的不是逼自己','每天只用30分钟，怎样把书里的方法真正用起来？','为什么家人一句话，就能让你一整天都不开心？','过了35岁，普通人如何重新找到生活目标？','读书不能变现？可能是你少做了这一步','她坚持7天后，第一次找回了久违的专注','“累了就躺平”真的能让人恢复吗？','把一本书变成一套可交付资料，要经过哪3步？','为什么忙了一整天，晚上却想不起做成了什么？','真正让人崩溃的，往往不是事情多','不是没时间，而是任务难度没有匹配能力','一个挑战清单，怎样救回被手机偷走的注意力？','孩子不专注时，父母最容易犯的一个错','人生下半场，比成功更重要的是什么？','把读书笔记做成打卡营，用户愿意为什么付费？','一个普通人的改变，为什么从小挑战开始？','每天都要高效，可能是一种新的自我消耗','7天行动卡应该卖知识，还是卖陪伴？','为什么越追求完美，越难进入真正的投入状态？','情绪低落时，先别急着给自己讲大道理','等有状态再开始，为什么会让你一直等？','用“目标—反馈—挑战”三步设计今天','伴侣不理解你的成长计划，应该怎么聊？','重新介绍自己：别再只说职业和家庭身份','同样是读书，为什么有人能做成长期收入？','她删掉10个目标后，反而完成了最重要的一件事','成年人需要沉浸，还是需要更彻底的休息？','这份30分钟练习表，解决的不是时间管理'];
let current=[];let selected=null;let documentContext='';let documentName='';const $=s=>document.querySelector(s);const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>b.classList.toggle('active'));
$('#uploadBtn').onclick=()=>$('#bookFile').click();$('#bookFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){e.target.value='';return toast('文档请控制在 20MB 以内')}documentName=file.name;const plain=/\.(txt|md)$/i.test(file.name);documentContext=plain?(await file.text()).slice(0,120000):`[待服务端解析的${file.name.split('.').pop().toUpperCase()}文档：${file.name}]`;const status=$('#uploadStatus');status.textContent=`✓ 已导入 ${file.name}（${(file.size/1024).toFixed(1)} KB）${plain?'，文本已提取':'，发布版将交由后端安全解析'}`;status.classList.add('ready')};
$('#bookForm').onsubmit=e=>{e.preventDefault();const book=$('#book').value.trim(),audience=$('#audience').value.trim();if(!book||!audience)return toast('请填写书名和目标用户');const btn=e.submitter;btn.classList.add('loading');btn.querySelector('span').textContent='正在理解你的用户…';setTimeout(()=>{render(book,audience);refreshCaseBooks();btn.classList.remove('loading');btn.querySelector('span').textContent='重新生成 30 个选题';$('#results').classList.remove('hidden');$('#results').scrollIntoView({behavior:'smooth'})},700)};
function render(book,audience){const groups=[['最关注的问题',['时间被切碎','付出缺少反馈','注意力分散','成长难坚持']],['情绪需求',['被理解','掌控感','价值感','确定性']],['付费动机',['节省整理时间','获得行动模板','陪伴监督','快速见效']]];$('#analysisTitle').textContent=`${audience}真正关心什么？`;$('#insights').innerHTML=groups.map(g=>`<article class="insight"><h3>${g[0]}</h3>${g[1].map(x=>`<span>${x}</span>`).join('')}</article>`).join('');const source=documentContext?`参考已导入的《${documentName}》材料提取观点`:`结合《${book}》中关于目标、反馈与投入的核心思路`;current=titles.map((t,i)=>({id:i,title:t.replace('{人群}',audience),category:categories[i%10],score:(9.7-(i%10)*.12).toFixed(1),book,pain:['付出很多但缺少反馈','碎片化休息无法恢复精力','知道方法却难行动'][i%3],insight:`${source}，正式发布前请结合原书核验具体表述。`,hook:t.replace('{人群}',audience),action:'选择一件难度适中、目标清晰的事，关闭提醒，连续投入30分钟并记录反馈。',quote:'真正消除疲惫的，不只是停下来，而是重新找回对生活的投入感。'}));draw(current);const project={book,audience,documentName,time:new Date().toLocaleString(),createdAt:Date.now()};localStorage.setItem('lastProject',JSON.stringify(project));const projects=JSON.parse(localStorage.getItem('bookProjects')||'[]').filter(p=>p.book!==book);localStorage.setItem('bookProjects',JSON.stringify([project,...projects].slice(0,30)))}
function draw(items){$('#topics').innerHTML=items.map(t=>`<article class="topic" data-id="${t.id}"><div class="meta"><span>${t.category}</span><b>${t.score}</b></div><h3>${t.title}</h3><p>${t.insight}</p></article>`).join('');document.querySelectorAll('.topic').forEach(e=>e.onclick=()=>openDetail(current[+e.dataset.id]))}
document.querySelectorAll('.filter button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter button').forEach(x=>x.classList.remove('active'));b.classList.add('active');draw(b.dataset.filter==='all'?current:current.filter(x=>x.category===b.dataset.filter))});
function openDetail(t){selected=t;$('#detailCategory').textContent=`${t.category} · 推荐指数 ${t.score}`;$('#detailTitle').textContent=t.title;$('#detailBody').innerHTML=[['用户痛点',t.pain],['书中观点',t.insight],['开头钩子',t.hook],['行动建议',t.action],['结尾金句',t.quote],['变现承接','7天行动打卡表 / 读书社群']].map(x=>`<div><small>${x[0]}</small>${x[1]}</div>`).join('');renderRelated(t);updateTodoButton();$('#detail').showModal()}
const relatedCatalog={
 '心流':['专注力','刻意练习','高效能人士的七个习惯','深度工作','掌控习惯'],
 '蓝筹孩子':['园丁与木匠','自驱型成长','正面管教','父母的语言','终身成长'],
 '专注力':['心流','深度工作','刻意练习','掌控习惯','认知觉醒']
};
function relatedFor(t){const base=relatedCatalog[t.book]||['心流','深度工作','刻意练习','终身成长','认知觉醒'];return base.filter(x=>x!==t.book).slice(0,5).map((book,i)=>({book,relevance:Math.max(72,96-i*5-(t.id%3))}))}
function renderRelated(t){const history=JSON.parse(localStorage.getItem('bookProjects')||'[]');$('#relatedBooks').innerHTML=relatedFor(t).map(r=>{const project=history.find(p=>p.book===r.book);return `<div class="related-book"><strong>《${r.book}》</strong><small>相关度 ${r.relevance}%</small><button ${project?'': 'disabled'} data-related="${r.book}">${project?'查看已拆主题':'尚未拆解'}</button></div>`}).join('');document.querySelectorAll('[data-related]:not([disabled])').forEach(b=>b.onclick=()=>openHistoryBook(b.dataset.related))}
function openHistoryBook(book){const project=JSON.parse(localStorage.getItem('bookProjects')||'[]').find(p=>p.book===book);if(!project)return;$('#detail').close();$('#book').value=project.book;$('#audience').value=project.audience;render(project.book,project.audience);$('#results').classList.remove('hidden');$('#results').scrollIntoView({behavior:'smooth'});toast(`已打开《${book}》的主题页`)}
const getTodos=()=>JSON.parse(localStorage.getItem('topicTodos')||'[]');const todoKey=t=>`${t.book}::${t.title}`;
function updateTodoButton(){const exists=getTodos().some(x=>x.key===todoKey(selected));$('#todoBtn').textContent=exists?'✓ 已加入选题待办':'＋ 加入选题待办';$('#todoBtn').disabled=exists}
$('#todoBtn').onclick=()=>{if(!selected)return;const todos=getTodos();const key=todoKey(selected);if(todos.some(x=>x.key===key))return;todos.push({key,topic:selected,addedAt:Date.now(),relevance:Number(selected.score)});localStorage.setItem('topicTodos',JSON.stringify(todos));updateTodoButton();renderTodos();toast('已加入选题待办')};
function renderTodos(){const mode=$('#todoSort').value;const todos=getTodos();todos.sort((a,b)=>mode==='time-asc'?a.addedAt-b.addedAt:mode==='book'?a.topic.book.localeCompare(b.topic.book,'zh-CN'):mode==='relevance'?b.relevance-a.relevance:b.addedAt-a.addedAt);$('#todoCount').textContent=todos.length;$('#todoList').innerHTML=todos.length?todos.map((x,i)=>`<article class="todo-item"><span class="todo-index">${String(i+1).padStart(2,'0')}</span><div><h3>${x.topic.title}</h3><p>《${x.topic.book}》 · ${x.topic.category} · 添加于 ${new Date(x.addedAt).toLocaleString()}</p></div><span class="todo-score">相关度 ${x.relevance}</span><button class="todo-remove" data-remove="${encodeURIComponent(x.key)}" aria-label="移除">×</button></article>`).join(''):'<div class="todo-empty">还没有待办选题。打开任意主题详情即可添加。</div>';document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeTodo(decodeURIComponent(b.dataset.remove)))}
function removeTodo(key){localStorage.setItem('topicTodos',JSON.stringify(getTodos().filter(x=>x.key!==key)));renderTodos();toast('已移出待办')}
$('#todoSort').onchange=renderTodos;renderTodos();
const getCases=()=>JSON.parse(localStorage.getItem('myCases')||'[]');
function refreshCaseBooks(){const projects=JSON.parse(localStorage.getItem('bookProjects')||'[]');const entered=$('#book').value.trim();const audience=$('#audience').value.trim();const all=entered?[{book:entered,audience},...projects.filter(p=>p.book!==entered)]:projects;const old=$('#caseBook').value;$('#caseBook').innerHTML='<option value="">暂不关联</option>'+all.map(p=>`<option value="${p.book}">《${p.book}》${p.book===entered?'（当前）':'（历史）'}</option>`).join('');if(all.some(p=>p.book===old))$('#caseBook').value=old;populateCaseTopics()}
function populateCaseTopics(){const book=$('#caseBook').value;const select=$('#caseTopic');if(!book){select.disabled=true;select.innerHTML='<option value="">请先选择书籍</option>';return}const project=JSON.parse(localStorage.getItem('bookProjects')||'[]').find(p=>p.book===book);const audience=project?.audience||$('#audience').value.trim()||'目标用户';const topicList=book===$('#book').value.trim()&&current.length?current:titles.map((t,i)=>({title:t.replace('{人群}',audience),score:(9.7-(i%10)*.12).toFixed(1)}));select.disabled=false;select.innerHTML='<option value="">只关联书籍</option>'+topicList.map(t=>`<option value="${t.title}">${t.title}</option>`).join('')}
$('#caseBook').onchange=populateCaseTopics;
$('#caseForm').onsubmit=e=>{e.preventDefault();const text=$('#caseText').value.trim();if(!text)return toast('请写下你的感想');const item={id:`case_${Date.now()}`,text,book:$('#caseBook').value,topic:$('#caseTopic').value,createdAt:Date.now()};localStorage.setItem('myCases',JSON.stringify([item,...getCases()].slice(0,100)));$('#caseText').value='';$('#caseBook').value='';populateCaseTopics();renderCases();toast('案例已保存')};
function renderCases(){const cases=getCases();$('#caseCount').textContent=cases.length;$('#caseList').innerHTML=cases.length?cases.map(c=>`<article class="case-card"><button class="case-delete" data-case-delete="${c.id}" aria-label="删除">×</button><time>${new Date(c.createdAt).toLocaleString()}</time><p>${escapeHtml(c.text)}</p><div class="case-association">${c.book?`<button data-case-open="${c.id}">《${c.book}》</button>`:''}${c.topic?`<button data-case-open="${c.id}">${c.topic}</button>`:''}${!c.book?'<span>未关联书籍</span>':''}</div></article>`).join(''):'<div class="todo-empty">还没有案例记录。</div>';document.querySelectorAll('[data-case-open]').forEach(b=>b.onclick=()=>openCaseLink(b.dataset.caseOpen));document.querySelectorAll('[data-case-delete]').forEach(b=>b.onclick=()=>{localStorage.setItem('myCases',JSON.stringify(getCases().filter(c=>c.id!==b.dataset.caseDelete)));renderCases();toast('案例已删除')})}
function escapeHtml(text){const el=document.createElement('div');el.textContent=text;return el.innerHTML}
function openCaseLink(id){const item=getCases().find(c=>c.id===id);if(!item?.book)return;const project=JSON.parse(localStorage.getItem('bookProjects')||'[]').find(p=>p.book===item.book);const audience=project?.audience||$('#audience').value.trim()||'目标用户';$('#book').value=item.book;$('#audience').value=audience;render(item.book,audience);refreshCaseBooks();$('#results').classList.remove('hidden');if(item.topic){const target=current.find(t=>t.title===item.topic);if(target)openDetail(target)}else $('#results').scrollIntoView({behavior:'smooth'});toast(`已打开《${item.book}》关联内容`)}
let recognition=null;let recording=false;const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
$('#voiceBtn').onclick=()=>{if(!SpeechRecognition)return toast('当前浏览器不支持语音转文字，请使用 Chrome 或 Edge');if(recording){recognition.stop();return}recognition=new SpeechRecognition();recognition.lang='zh-CN';recognition.continuous=true;recognition.interimResults=true;const original=$('#caseText').value;recognition.onstart=()=>{recording=true;$('#voiceBtn').classList.add('recording');$('#voiceBtn').textContent='■ 停止语音记录';$('#voiceStatus').textContent='正在聆听…'};recognition.onresult=e=>{let finalText='',interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript;e.results[i].isFinal?finalText+=text:interim+=text}if(finalText)$('#caseText').value+=finalText;$('#voiceStatus').textContent=interim||'正在聆听…'};recognition.onerror=e=>{toast(e.error==='not-allowed'?'请允许麦克风权限后重试':'语音识别暂时不可用')};recognition.onend=()=>{recording=false;$('#voiceBtn').classList.remove('recording');$('#voiceBtn').textContent='● 开始语音记录';$('#voiceStatus').textContent='语音已转为文字，可继续编辑'};recognition.start()};
refreshCaseBooks();renderCases();
const quoteSeeds=['你不需要突然成为更好的人，只需要每天完成一次对自己的承诺。','真正的休息，不只是停止忙碌，而是重新找回对生活的投入。','当目标足够清晰，焦虑就会慢慢让位给行动。','成长不是逃离现在的身份，而是在身份之外重新看见自己。','专注不是天赋，是你为重要之事主动留出的空间。','比坚持更重要的，是把挑战调到你愿意再次开始的难度。','没有反馈的付出最容易耗尽人，微小成果会把力量还给你。','别用别人的节奏判断自己，你需要的是适合当下生活的成长方式。','知识真正属于你的那一刻，是它开始改变一个具体行动的时候。','最有价值的改变，往往始于一段不被打扰的短暂投入。'];
$('#quotesBtn').onclick=()=>{const book=$('#book').value.trim(),audience=$('#audience').value.trim();if(!book||!audience)return toast('请先填写书名和目标用户');$('#quotesNote').textContent=`为《${book}》与${audience}生成 · 观点转述，非书籍原文`;$('#quotesGrid').innerHTML=quoteSeeds.map((q,i)=>`<article class="quote-card"><b>${String(i+1).padStart(2,'0')}</b><span>${q}</span><small>《${book}》观点二创 · 适合${audience}</small><button class="quote-share" data-quote-image="${i}">生成社交媒体图片</button></article>`).join('');document.querySelectorAll('[data-quote-image]').forEach(b=>b.onclick=()=>generateQuoteImage(Number(b.dataset.quoteImage)));$('#quotes').classList.remove('hidden');$('#quotes').scrollIntoView({behavior:'smooth'})};
let currentShareIndex=0;function audienceTheme(audience){if(/妈妈|女性|宝妈|女孩/.test(audience))return{name:'温暖成长风',colors:['#f2d6c7','#b95746','#6d352f'],accent:'#fff5e9'};if(/孩子|学生|青少年/.test(audience))return{name:'清新活力风',colors:['#dce8bd','#47705a','#e8b85b'],accent:'#fffbe8'};if(/职场|管理|创业|老板/.test(audience))return{name:'理性专业风',colors:['#d8d4c8','#263c4a','#c89c4a'],accent:'#f7f1df'};return{name:'安静阅读风',colors:['#e8dfcf','#344c3d','#b76548'],accent:'#fffaf0'}}
function generateQuoteImage(index){currentShareIndex=index;const canvas=$('#quoteCanvas'),ctx=canvas.getContext('2d'),quote=quoteSeeds[index],book=$('#book').value.trim(),audience=$('#audience').value.trim(),theme=audienceTheme(audience);const g=ctx.createLinearGradient(0,0,1080,1440);g.addColorStop(0,theme.colors[0]);g.addColorStop(1,theme.accent);ctx.fillStyle=g;ctx.fillRect(0,0,1080,1440);ctx.globalAlpha=.18;ctx.fillStyle=theme.colors[1];ctx.beginPath();ctx.arc(900,180,330,0,Math.PI*2);ctx.fill();ctx.fillStyle=theme.colors[2];ctx.beginPath();ctx.arc(100,1320,280,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=theme.colors[1];ctx.lineWidth=4;ctx.strokeRect(70,70,940,1300);ctx.fillStyle=theme.colors[1];ctx.font='700 30px "Microsoft YaHei"';ctx.fillText('真读 · READ FOR REAL',120,155);ctx.font='900 150px Georgia';ctx.globalAlpha=.16;ctx.fillText('“',110,430);ctx.globalAlpha=1;ctx.font='700 66px "Microsoft YaHei"';drawWrappedText(ctx,quote,130,485,820,105);ctx.fillStyle=theme.colors[2];ctx.fillRect(130,1045,90,8);ctx.fillStyle=theme.colors[1];ctx.font='500 30px "Microsoft YaHei"';ctx.fillText(`《${book}》观点二创`,130,1125);ctx.font='400 26px "Microsoft YaHei"';ctx.fillText(`为 ${audience} 而写`,130,1180);ctx.font='400 22px "Microsoft YaHei"';ctx.globalAlpha=.65;ctx.fillText('观点转述 · 非书籍原文引用',130,1290);ctx.globalAlpha=1;$('#shareStyleNote').textContent=`已为“${audience}”匹配${theme.name} · 1080 × 1440`;$('#shareImageDialog').showModal()}
function drawWrappedText(ctx,text,x,y,maxWidth,lineHeight){const chars=[...text];let line='';let cursorY=y;for(const char of chars){const test=line+char;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,cursorY);line=char;cursorY+=lineHeight}else line=test}if(line)ctx.fillText(line,x,cursorY)}
$('.share-close').onclick=()=>$('#shareImageDialog').close();$('#downloadImageBtn').onclick=()=>{$('#quoteCanvas').toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`真读-金句${currentShareIndex+1}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('高清分享图已下载')},'image/png')};
$('.close').onclick=()=>$('#detail').close();$('#copyBtn').onclick=async()=>{await navigator.clipboard.writeText(`${selected.title}\n${selected.insight}\n${selected.action}\n${selected.quote}`);toast('选题已复制')};$('#caseNavBtn').onclick=()=>$('#cases').scrollIntoView({behavior:'smooth'});$('#historyBtn').onclick=()=>{const h=JSON.parse(localStorage.getItem('lastProject')||'null');toast(h?`上次拆书：${h.book} · ${h.time}`:'还没有历史记录')};
