(()=>{
'use strict';
const root=document.querySelector('#pattern-studio');if(!root)return;
const presets={
  xhs:{label:'小红书封面',width:1080,height:1440,ratio:'3:4'},
  douyin:{label:'抖音封面',width:1080,height:1920,ratio:'9:16'},
  moments:{label:'朋友圈背景',width:1080,height:1080,ratio:'1:1'},
  channels:{label:'视频号封面',width:1080,height:1260,ratio:'6:7'},
  instagram:{label:'INS 帖子',width:1080,height:1350,ratio:'4:5'},
  wechat:{label:'公众号封面',width:1175,height:500,ratio:'2.35:1'}
};
const palettes=[
  ['#f8e5cf','#d8664c','#1f5148','#f3b65c','#fff9ef'],
  ['#e5efe9','#2f6f61','#d6a646','#d97763','#fbf7ee'],
  ['#e9e6f2','#5a5188','#e07a83','#3f786e','#fffaf3'],
  ['#172d2b','#347f68','#f0c25f','#d35f49','#f8f0de'],
  ['#f5dfdf','#b34d67','#3d6681','#e6a94d','#fff8ed']
];
const state={files:[],platforms:new Set(['xhs']),format:'image/png',variation:0,outputs:[]};
const $=selector=>root.querySelector(selector),fileInput=$('#patternFiles'),status=$('#patternStatus');
const hash=value=>{let h=2166136261;for(const ch of String(value)){h^=ch.codePointAt(0);h=Math.imul(h,16777619)}return h>>>0};
const random=seed=>()=>((seed=Math.imul(seed^seed>>>15,1|seed),seed^=seed+Math.imul(seed^seed>>>7,61|seed),((seed^seed>>>14)>>>0)/4294967296));
const ext=name=>(name.split('.').pop()||'').toLowerCase();
const sizeLabel=bytes=>bytes>1048576?`${(bytes/1048576).toFixed(1)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`;
function setStatus(message,type=''){status.textContent=message;status.className=`pattern-status ${type}`.trim()}
function escapeText(value){return String(value||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function customRatio(width,height){const value=width/height;return value>=1?`${Number(value.toFixed(2))}:1`:`1:${Number((1/value).toFixed(2))}`}
function customPreset(reportError=true){const width=Number($('#patternCustomWidth').value),height=Number($('#patternCustomHeight').value);if(!Number.isInteger(width)||!Number.isInteger(height)||width<320||height<320||width>4096||height>4096){if(reportError)setStatus('自定义宽高需为 320—4096 之间的整数像素。','error');return null}return{label:'自定义尺寸',width,height,ratio:customRatio(width,height)}}
function selectedPresets(reportError=true){const result=[];for(const key of state.platforms){const preset=key==='custom'?customPreset(reportError):presets[key];if(!preset)return null;result.push({key,preset})}return result}
function updateSelectionSummary(){const items=selectedPresets(false);if(!items)return;$('#patternSizeBadge').textContent=`已选择 ${items.length} 个尺寸`;$('#patternCustomSize').hidden=!state.platforms.has('custom')}
function clearOutputs(){state.outputs=[];$('#patternPreviewGrid').innerHTML='<div id="patternEmpty" class="pattern-preview-empty"><b>等待生成</b>选择一个或多个尺寸，再生成整组图案。</div>';toggleDownload(false)}
function toggleDownload(enabled){$('#patternDownload').disabled=!enabled;$('#patternVariant').disabled=!enabled}
function renderFiles(){const list=$('#patternFileList');if(!state.files.length){list.innerHTML='<div class="pattern-empty-file">尚未添加素材，也可以只用描述生成抽象图案。</div>';return}list.innerHTML=state.files.map((item,i)=>`<div class="pattern-file-item"><small>${item.kind==='image'?'图片':'文档'}</small><span title="${escapeText(item.file.name)}">${escapeText(item.file.name)}</span><small>${sizeLabel(item.file.size)}</small><button type="button" data-remove-pattern="${i}" aria-label="移除 ${escapeText(item.file.name)}">×</button></div>`).join('');list.querySelectorAll('[data-remove-pattern]').forEach(button=>button.onclick=()=>{const index=Number(button.dataset.removePattern),item=state.files[index];if(item?.bitmap?.close)item.bitmap.close();state.files.splice(index,1);renderFiles();clearOutputs()})}
async function imageBitmap(file){if('createImageBitmap'in window)return createImageBitmap(file);return new Promise((resolve,reject)=>{const img=new Image,url=URL.createObjectURL(file);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('图片无法读取'))};img.src=url})}
async function documentText(file){const extension=ext(file.name),buffer=await file.arrayBuffer();if(extension==='pdf'){if(!window.pdfjsLib)throw new Error('PDF 解析组件尚未加载');const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(buffer)}).promise;let text='';for(let i=1;i<=Math.min(pdf.numPages,18);i++){const page=await pdf.getPage(i),content=await page.getTextContent();text+=content.items.map(item=>item.str).join(' ')+'\n'}return text}if(extension==='docx'){if(!window.mammoth)throw new Error('DOCX 解析组件尚未加载');return(await window.mammoth.extractRawText({arrayBuffer:buffer})).value||''}const raw=new TextDecoder('utf-8',{fatal:false}).decode(buffer);if(['html','htm','fb2','rtf'].includes(extension)){const doc=new DOMParser().parseFromString(raw,'text/html');return doc.body?.textContent||raw}return raw}
async function ingest(files){const incoming=[...files].slice(0,Math.max(0,6-state.files.length));if(!incoming.length)return;setStatus('正在读取上传素材…');for(const file of incoming){if(file.size>50*1024*1024){setStatus(`${file.name} 超过 50MB，已跳过。`,'error');continue}try{if(file.type.startsWith('image/')||['jpg','jpeg','png','webp','gif','svg'].includes(ext(file.name))){state.files.push({file,kind:'image',bitmap:await imageBitmap(file),text:''})}else{const text=(await documentText(file)).replace(/\s+/g,' ').trim().slice(0,50000);if(text.length<10)throw new Error('没有读取到足够文字');state.files.push({file,kind:'document',text})}}catch(error){setStatus(`${file.name} 读取失败：${error.message}`,'error')}}renderFiles();clearOutputs();if(state.files.length)setStatus(`已准备 ${state.files.length} 个素材，可选择多个尺寸生成。`,'success')}
function paletteFor(text,seed){const value=text.toLowerCase();if(/黑|夜|高级|深色|dark|night/.test(value))return palettes[3];if(/自然|森林|清新|绿色|nature|green/.test(value))return palettes[1];if(/温暖|日落|橙|热烈|warm|sunset/.test(value))return palettes[0];if(/浪漫|粉|柔和|少女|pink|soft/.test(value))return palettes[4];return palettes[seed%palettes.length]}
function coverRect(iw,ih,x,y,w,h){const scale=Math.max(w/iw,h/ih),dw=iw*scale,dh=ih*scale;return[x+(w-dw)/2,y+(h-dh)/2,dw,dh]}
function containRect(iw,ih,x,y,w,h){const scale=Math.min(w/iw,h/ih),dw=iw*scale,dh=ih*scale;return[x+(w-dw)/2,y+(h-dh)/2,dw,dh]}
function roundPath(context,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);context.beginPath();context.moveTo(x+rr,y);context.arcTo(x+w,y,x+w,y+h,rr);context.arcTo(x+w,y+h,x,y+h,rr);context.arcTo(x,y+h,x,y,rr);context.arcTo(x,y,x+w,y,rr);context.closePath()}
function drawImage(context,image,x,y,w,h,mode='cover',radius=32){context.save();roundPath(context,x,y,w,h,radius);context.clip();context.fillStyle='#f7f1e8';context.fillRect(x,y,w,h);const rect=(mode==='contain'?containRect:coverRect)(image.width,image.height,x,y,w,h);context.drawImage(image,...rect);context.restore()}
function drawBackdrop(context,width,height,palette,rand){const gradient=context.createLinearGradient(0,0,width,height);gradient.addColorStop(0,palette[0]);gradient.addColorStop(.52,palette[4]);gradient.addColorStop(1,palette[2]);context.fillStyle=gradient;context.fillRect(0,0,width,height);for(let i=0;i<7;i++){const x=rand()*width,y=rand()*height,r=(.12+rand()*.26)*Math.min(width,height),g=context.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,`${palette[(i+1)%4]}b8`);g.addColorStop(1,`${palette[(i+1)%4]}00`);context.fillStyle=g;context.beginPath();context.arc(x,y,r,0,Math.PI*2);context.fill()}context.save();context.globalAlpha=.16;context.strokeStyle=palette[2];context.lineWidth=Math.max(2,width/420);for(let i=0;i<9;i++){const y=(i+.4)*height/9;context.beginPath();context.moveTo(-width*.1,y);context.bezierCurveTo(width*.28,y-height*.1*(rand()-.5),width*.7,y+height*.12*(rand()-.5),width*1.1,y-height*.05);context.stroke()}context.restore()}
function drawShapes(context,width,height,palette,rand){context.save();context.globalCompositeOperation='multiply';for(let i=0;i<12;i++){const x=rand()*width,y=rand()*height,w=width*(.06+rand()*.19),h=height*(.035+rand()*.12),turn=(rand()-.5)*.8;context.save();context.translate(x,y);context.rotate(turn);context.globalAlpha=.16+rand()*.18;context.fillStyle=palette[(i+1)%4];roundPath(context,-w/2,-h/2,w,h,Math.min(w,h)*.45);context.fill();context.restore()}context.restore();context.save();context.globalAlpha=.42;context.lineCap='round';for(let i=0;i<18;i++){context.strokeStyle=palette[(i+2)%4];context.lineWidth=Math.max(2,width*(.002+rand()*.004));const x=rand()*width,y=rand()*height,l=width*(.025+rand()*.075);context.beginPath();context.moveTo(x-l/2,y);context.quadraticCurveTo(x,y-l*(.3+rand()),x+l/2,y+(rand()-.5)*l*.25);context.stroke()}context.restore()}
function drawImages(context,images,width,height,variation){if(!images.length)return;const margin=width*.075,usableW=width-margin*2,usableH=height*.64,startY=height*.18;context.save();context.shadowColor='#1c241f55';context.shadowBlur=width*.035;context.shadowOffsetY=height*.018;if(images.length===1){const portrait=height>width*1.3,x=margin+(variation%2?usableW*.08:0),y=startY+(variation%3)*height*.025,w=usableW*(variation%2?.84:.92),h=usableH*(portrait?.78:.72);drawImage(context,images[0],x,y,w,h,'cover',width*.035)}else{const gap=width*.025,cellW=(usableW-gap)/2,cellH=Math.min(usableH*.42,cellW*1.18);images.slice(0,4).forEach((image,i)=>{const col=i%2,row=Math.floor(i/2),offset=(variation+i)%3*height*.012;drawImage(context,image,margin+col*(cellW+gap),startY+row*(cellH+gap)+offset,cellW,cellH,'cover',width*.028)})}context.restore()}
function drawDocMotif(context,text,width,height,palette,rand){if(!text)return;const words=(text.match(/[\u4e00-\u9fff]{2,6}|[A-Za-z]{4,}/g)||[]).filter((word,i,array)=>array.indexOf(word)===i).slice(0,6);context.save();context.globalAlpha=.12;context.fillStyle=palette[2];context.textAlign='center';words.forEach((word,i)=>{context.font=`800 ${Math.round(width*(.055+rand()*.055))}px -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif`;context.fillText(word,width*(.18+rand()*.64),height*(.22+i*.1))});context.restore()}
function drawHeadline(context,text,width,height,palette){const value=text.trim();if(!value)return;const max=[...value].slice(0,24).join(''),fontSize=Math.round(width*(max.length>16?.052:max.length>9?.065:.078)),maxWidth=width*.78,x=width*.1,y=height*.1;context.save();context.fillStyle='#fffdf6e8';roundPath(context,x-width*.025,y-fontSize*.9,maxWidth+width*.05,fontSize*1.65,width*.02);context.fill();context.fillStyle=palette[2];context.font=`800 ${fontSize}px -apple-system,BlinkMacSystemFont,"PingFang SC","Microsoft YaHei",sans-serif`;context.textAlign='left';context.textBaseline='middle';let line='',lineY=y;for(const char of max){const test=line+char;if(context.measureText(test).width>maxWidth&&line){context.fillText(line,x,lineY);line=char;lineY+=fontSize*1.25}else line=test}if(line)context.fillText(line,x,lineY);context.restore()}
function drawTexture(context,width,height,rand){context.save();context.globalAlpha=.07;for(let i=0;i<Math.min(1600,Math.round(width*height/1200));i++){context.fillStyle=rand()>.5?'#0e221a':'#fff';const size=.5+rand()*1.8;context.fillRect(rand()*width,rand()*height,size,size)}context.restore()}
function renderArtwork(canvas,key,preset,index,prompt,headline,source){const context=canvas.getContext('2d'),seed=hash(`${prompt}|${source}|${key}|${preset.width}x${preset.height}|${state.variation}|${index}`),rand=random(seed),palette=paletteFor(`${prompt} ${source}`,seed);canvas.width=preset.width;canvas.height=preset.height;drawBackdrop(context,canvas.width,canvas.height,palette,rand);drawShapes(context,canvas.width,canvas.height,palette,rand);drawDocMotif(context,state.files.filter(item=>item.kind==='document').map(item=>item.text).join(' '),canvas.width,canvas.height,palette,rand);drawImages(context,state.files.filter(item=>item.kind==='image').map(item=>item.bitmap),canvas.width,canvas.height,state.variation+index);drawHeadline(context,headline,canvas.width,canvas.height,palette);drawTexture(context,canvas.width,canvas.height,rand)}
function outputCard(key,preset,index,prompt,headline,source){const figure=document.createElement('figure'),caption=document.createElement('figcaption'),canvas=document.createElement('canvas'),button=document.createElement('button');figure.className='pattern-preview-card';caption.innerHTML=`<strong>${escapeText(preset.label)}</strong><small>${preset.width} × ${preset.height} · ${preset.ratio}</small>`;canvas.setAttribute('aria-label',`${preset.label}预览`);renderArtwork(canvas,key,preset,index,prompt,headline,source);button.type='button';button.textContent='下载此尺寸';const output={key,preset,canvas};button.onclick=()=>downloadOutput(output);figure.append(caption,canvas,button);return{figure,output}}
function render(){const prompt=$('#patternPrompt').value.trim(),headline=$('#patternHeadline').value.trim();if(!prompt){setStatus('请先写下希望生成的画面、气质或用途。','error');$('#patternPrompt').focus();return}const selected=selectedPresets();if(!selected?.length){setStatus('请至少选择一个发布尺寸。','error');return}const source=state.files.map(item=>`${item.file.name} ${item.text||''}`).join(' ').slice(0,50000),grid=$('#patternPreviewGrid');grid.innerHTML='';state.outputs=[];selected.forEach(({key,preset},index)=>{const card=outputCard(key,preset,index,prompt,headline,source);grid.append(card.figure);state.outputs.push(card.output)});toggleDownload(true);$('#patternSizeBadge').textContent=`已生成 ${state.outputs.length} 个尺寸`;setStatus(`已同时生成 ${state.outputs.length} 张图案，可分别下载或下载全部。`,'success')}
function downloadOutput(output,delay=0){return new Promise(resolve=>setTimeout(()=>{const mime=state.format,extension=mime==='image/jpeg'?'jpg':mime==='image/webp'?'webp':'png',quality=mime==='image/png'?undefined:.94;output.canvas.toBlob(blob=>{if(!blob){setStatus(`${output.preset.label} 导出失败，请重试。`,'error');resolve();return}const link=document.createElement('a'),url=URL.createObjectURL(blob);link.href=url;link.download=`真读-${output.preset.label}-${output.preset.width}x${output.preset.height}-${Date.now()}.${extension}`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1200);resolve()},mime,quality)},delay))}
async function downloadAll(){if(!state.outputs.length)return;for(let i=0;i<state.outputs.length;i++)await downloadOutput(state.outputs[i],i?180:0);setStatus(`已下载 ${state.outputs.length} 张 ${state.format.split('/')[1].toUpperCase()} 图片。`,'success')}
$('#patternUploadBtn').onclick=()=>fileInput.click();fileInput.onchange=async event=>{await ingest(event.target.files);event.target.value=''};
root.querySelectorAll('.pattern-platform').forEach(button=>button.onclick=()=>{const key=button.dataset.patternPlatform;if(state.platforms.has(key)){if(state.platforms.size===1){setStatus('至少保留一个发布尺寸。','error');return}state.platforms.delete(key);button.classList.remove('active')}else{state.platforms.add(key);button.classList.add('active')}updateSelectionSummary();clearOutputs();setStatus(`已选择 ${state.platforms.size} 个尺寸，点击“生成图案”同时生成。`)});
['#patternCustomWidth','#patternCustomHeight'].forEach(selector=>$(selector).onchange=()=>{if(!state.platforms.has('custom'))return;const preset=customPreset();clearOutputs();if(preset){updateSelectionSummary();setStatus(`自定义尺寸已设为 ${preset.width}×${preset.height}，点击生成应用到整组图案。`)}});
$('#patternFormat').onchange=event=>{state.format=event.target.value};$('#patternGenerate').onclick=render;$('#patternVariant').onclick=()=>{state.variation++;render()};$('#patternDownload').onclick=downloadAll;renderFiles();updateSelectionSummary();
})();
