const json=(data,status=200,origin='*')=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','access-control-allow-origin':origin,'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type'}})
const normalize=s=>String(s||'').toLowerCase().replace(/[《》\s:：·,.，。!！?？()（）\-_]/g,'')
const exactish=(a,b)=>{a=normalize(a);b=normalize(b);return a===b||(a.length>2&&b.includes(a))||(b.length>2&&a.includes(b))}
async function lookupBook(bookName){
 const q=encodeURIComponent(bookName);const [google,open]=await Promise.allSettled([
  fetch(`https://www.googleapis.com/books/v1/volumes?q=intitle:${q}&maxResults=5&printType=books`).then(r=>r.ok?r.json():null),
  fetch(`https://openlibrary.org/search.json?title=${q}&limit=5&fields=title,author_name,first_publish_year,subject,key`).then(r=>r.ok?r.json():null)
 ]);
 const volumes=google.status==='fulfilled'?(google.value?.items||[]):[];const g=volumes.find(v=>exactish(v.volumeInfo?.title,bookName));const docs=open.status==='fulfilled'?(open.value?.docs||[]):[];const o=docs.find(v=>exactish(v.title,bookName));
 if(!g&&!o)return{matched:false,code:'NO_CONTENT'};
 const info=g?.volumeInfo||{};const description=String(info.description||'').replace(/<[^>]+>/g,' ').trim();const subjects=[...(info.categories||[]),...(o?.subject||[])].slice(0,15);
 const sourceText=[`书名：${info.title||o?.title||bookName}`,`作者：${(info.authors||o?.author_name||[]).join('、')}`,`首次出版：${info.publishedDate||o?.first_publish_year||'未知'}`,`主题：${subjects.join('、')}`,description&&`公开简介：${description}`].filter(Boolean).join('\n');
 if(!description&&subjects.length<3)return{matched:false,code:'NO_CONTENT',metadataOnly:true};
 return{matched:true,sourceType:'catalog',sourceText,book:{title:info.title||o?.title||bookName,authors:info.authors||o?.author_name||[],description,subjects},sources:[g?.selfLink,o?.key&&`https://openlibrary.org${o.key}`].filter(Boolean)}
}
const topicSchema={type:'object',additionalProperties:false,required:['audienceAnalysis','topics'],properties:{audienceAnalysis:{type:'object',additionalProperties:false,required:['mainProblems','emotionalNeeds','lifeScenarios','paymentMotivations'],properties:{mainProblems:{type:'array',items:{type:'string'}},emotionalNeeds:{type:'array',items:{type:'string'}},lifeScenarios:{type:'array',items:{type:'string'}},paymentMotivations:{type:'array',items:{type:'string'}}}},topics:{type:'array',minItems:5,maxItems:5,items:{type:'object',additionalProperties:false,required:['title','shortTitle','article','category','painPoint','bookInsight','hook','actionAdvice','goldenSentence','score'],properties:{title:{type:'string'},shortTitle:{type:'string'},article:{type:'string'},category:{type:'string'},painPoint:{type:'string'},bookInsight:{type:'string'},hook:{type:'string'},actionAdvice:{type:'string'},goldenSentence:{type:'string'},score:{type:'number'}}}}}}
const articleRewriteSchema={type:'object',additionalProperties:false,required:['title','shortTitle','article'],properties:{title:{type:'string'},shortTitle:{type:'string'},article:{type:'string'}}};const videoRewriteSchema={type:'object',additionalProperties:false,required:['segments','bgm'],properties:{segments:{type:'array',minItems:5,maxItems:6,items:{type:'object',additionalProperties:false,required:['time','role','text','expression','speed','tone'],properties:{time:{type:'string'},role:{type:'string'},text:{type:'string'},expression:{type:'string'},speed:{type:'string'},tone:{type:'string'}}}},bgm:{type:'string'}}}
async function searchPublicWeb(bookName){const catalog=await lookupBook(bookName);if(catalog.matched)return catalog;const q=encodeURIComponent(`intitle:${bookName}`);const url=`https://zh.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${q}&gsrlimit=5&prop=extracts&exintro=1&explaintext=1&redirects=1&format=json&origin=*`;const r=await fetch(url,{headers:{'user-agent':'TrueRead/1.0'}});const data=r.ok?await r.json():null;const pages=Object.values(data?.query?.pages||{});const page=pages.find(x=>exactish(x.title,bookName))||pages.find(x=>normalize(x.title).includes(normalize(bookName)));const extract=String(page?.extract||'').trim();if(!page||extract.length<120)return{matched:false,code:'NO_CONTENT'};return{matched:true,sourceType:'web_search',sourceText:`书名：${page.title}\n公开百科资料：${extract.slice(0,20000)}`,book:{title:page.title,authors:[],description:extract,subjects:[]},sources:[`https://zh.wikipedia.org/?curid=${page.pageid}`]}}
async function callAI(env,input){if(!env.DEEPSEEK_API_KEY)throw Object.assign(new Error('DeepSeek 服务尚未配置'),{status:503,code:'AI_NOT_CONFIGURED'});const system=`你是资深拆书内容策划师。必须只输出合法 JSON，不要 Markdown。输出必须符合这个 JSON Schema。topics 必须严格生成5项，按1到5逐项构思，不可少于或多于5项：${JSON.stringify(topicSchema)}`;for(let attempt=1;attempt<=2;attempt++){const user=attempt===1?input:`${input}\n这是自动重试：上次返回不完整。请检查5个选题及所有必填字段，再输出恰好5个完整 topics。`;const body={model:env.DEEPSEEK_MODEL||'deepseek-v4-flash',messages:[{role:'system',content:system},{role:'user',content:user}],response_format:{type:'json_object'},thinking:{type:'disabled'},max_tokens:12000};const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{authorization:`Bearer ${env.DEEPSEEK_API_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data?.error?.message||'DeepSeek 请求失败'),{status:r.status,code:'AI_ERROR'});const text=data?.choices?.[0]?.message?.content;if(!text){if(attempt<2)continue;throw Object.assign(new Error('DeepSeek 未返回结构化内容'),{status:502,code:'EMPTY_AI_RESPONSE'})}let parsed;try{parsed=JSON.parse(text)}catch{if(attempt<2)continue;throw Object.assign(new Error('DeepSeek 返回内容不是有效 JSON'),{status:502,code:'INVALID_AI_RESPONSE'})}if(Array.isArray(parsed.topics)&&parsed.topics.length===5)return parsed}throw Object.assign(new Error('DeepSeek 连续两次未生成恰好5个选题，请稍后重试'),{status:502,code:'INVALID_TOPIC_COUNT'})}
function prompt({bookName,audience,sourceText,sourceType,platform='小红书'}){const rules={小红书:'标题有收藏感和具体生活场景，表达真诚克制，不使用夸张营销词；hook像朋友分享，适合图文或口播。shortTitle和article必须为空字符串。',视频号:'标题稳重可信，观点完整，适合30岁以上用户和熟人传播；hook不浮夸，强调经历、关系与长期价值。shortTitle和article必须为空字符串。',抖音:'标题短、冲突或反差明确，前3秒hook直接给痛点或结论，表达节奏快、行动明确。shortTitle和article必须为空字符串。',公众号:'生成适合微信公众号深度阅读的纯文字内容。title为完整文章标题；shortTitle为18字以内短标题；article为结构完整、自然分段的中文文章，包含引入、问题展开、书中观点、现实案例式场景、具体行动和结尾，不使用Markdown符号，不超过2000个汉字，不捏造原文。hook作为文章导语。'};return `你是资深拆书内容策划师。根据提供的${sourceType==='document'?'用户上传书籍文档':'可验证公开资料'}，为目标用户生成恰好5个不重复选题。禁止补写来源中没有的具体原文、章节或作者观点；bookInsight必须是来源内容的谨慎转述。每个主题只解决一个具体问题。\n发布平台：${platform}\n平台规则：${rules[platform]||rules.小红书}\n书名：${bookName}\n目标用户：${audience}\n来源材料：\n${sourceText.slice(0,120000)}`}
async function callRewrite(env,{contentType,platform,bookName,audience,style,source}){if(!env.DEEPSEEK_API_KEY)throw Object.assign(new Error('DeepSeek 服务尚未配置'),{status:503,code:'AI_NOT_CONFIGURED'});const schema=contentType==='article'?articleRewriteSchema:videoRewriteSchema;const system=`你是中文内容改写编辑。只输出合法JSON，不要Markdown，严格符合Schema：${JSON.stringify(schema)}。只改变表达风格，不得增删或编造书籍事实、个人案例、时间结构和核心观点。`;const sourceText=JSON.stringify(source).slice(0,30000);const requirement=contentType==='article'?'保留微信公众号的标题、18字以内短标题和自然分段纯文字正文；article不超过2000个汉字。':'保留每段time和role；结合所选平台调整用词与节奏；必须保留个人案例段；总口播时长仍为1分钟，并同步调整表情、语速、语气和BGM。';const body={model:env.DEEPSEEK_MODEL||'deepseek-v4-flash',messages:[{role:'system',content:system},{role:'user',content:`内容类型：${contentType}\n平台：${platform}\n书名：${bookName}\n目标用户：${audience}\n用户要求的风格：${style}\n要求：${requirement}\n待改写内容：${sourceText}`}],response_format:{type:'json_object'},thinking:{type:'disabled'},max_tokens:contentType==='article'?6000:4000};const r=await fetch('https://api.deepseek.com/chat/completions',{method:'POST',headers:{authorization:`Bearer ${env.DEEPSEEK_API_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Object.assign(new Error(data?.error?.message||'DeepSeek 请求失败'),{status:r.status,code:'AI_ERROR'});let parsed;try{parsed=JSON.parse(data?.choices?.[0]?.message?.content||'')}catch{throw Object.assign(new Error('AI 未返回有效的风格调整内容'),{status:502,code:'INVALID_AI_RESPONSE'})}if(contentType==='article'){parsed.title=String(parsed.title||'').slice(0,80);parsed.shortTitle=String(parsed.shortTitle||'').slice(0,18);parsed.article=String(parsed.article||'').slice(0,2000)}return parsed}
export default{async fetch(request,env){const origin=request.headers.get('origin')||'';const allowed=env.ALLOWED_ORIGIN||'*';const cors=allowed==='*'||origin.startsWith(allowed)?origin||allowed:allowed;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':cors,'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400'}});if(request.method!=='POST')return json({ok:false,message:'Method not allowed'},405,cors);try{const url=new URL(request.url),body=await request.json(),platform=['小红书','视频号','抖音','公众号'].includes(body.platform)?body.platform:'小红书';if(url.pathname==='/api/lookup'){if(!body.bookName?.trim())return json({ok:false,message:'请填写书名'},400,cors);return json({ok:true,data:await lookupBook(body.bookName.trim())},200,cors)}if(url.pathname==='/api/generate'){if(!body.bookName?.trim()||!body.audience?.trim()||!body.sourceText?.trim())return json({ok:false,message:'缺少书名、目标用户或来源材料'},400,cors);const data=await callAI(env,prompt({...body,platform,sourceType:body.sourceType||'document'}));return json({ok:true,data,platform,sourceType:body.sourceType||'document'},200,cors)}if(url.pathname==='/api/web-search'){if(!body.bookName?.trim()||!body.audience?.trim()||body.userConsent!==true)return json({ok:false,message:'网页搜索需要用户明确授权'},400,cors);const source=await searchPublicWeb(body.bookName.trim());if(!source.matched)return json({ok:false,code:'NO_CONTENT',message:'无检索内容'},404,cors);const data=await callAI(env,prompt({bookName:body.bookName.trim(),audience:body.audience.trim(),platform,sourceText:source.sourceText,sourceType:'web_search'}));return json({ok:true,data,platform,sourceType:'web_search',sources:source.sources},200,cors)}if(url.pathname==='/api/rewrite'){const contentType=body.contentType==='article'?'article':body.contentType==='video'?'video':'';const style=String(body.style||'').trim().slice(0,80);if(!contentType||!style||!body.source||typeof body.source!=='object')return json({ok:false,message:'缺少内容类型、风格要求或原始内容'},400,cors);const data=await callRewrite(env,{contentType,platform,bookName:String(body.bookName||'').slice(0,100),audience:String(body.audience||'').slice(0,200),style,source:body.source});return json({ok:true,data,platform},200,cors)}return json({ok:false,message:'Not found'},404,cors)}catch(e){console.error(JSON.stringify({message:e.message,code:e.code,status:e.status}));return json({ok:false,code:e.code||'SERVER_ERROR',message:e.message||'服务暂不可用'},e.status||500,cors)}}}
